services:
  keycloak:
    image: quay.io/keycloak/keycloak:26.7.3
    command: start-dev --import-realm
    environment:
      KC_BOOTSTRAP_ADMIN_USERNAME: admin
      KC_BOOTSTRAP_ADMIN_PASSWORD: admin
    volumes:
      - ./keycloak/realm-export.json:/opt/keycloak/data/import/realm-export.json:ro
    ports:
      - "8081:8080"

  redis:
    image: redis:8-alpine
    ports:
      - "6379:6379"
